services:
  solar-monitor:
    image: ghcr.io/acamposcar/solar:latest
    container_name: solar-monitor
    restart: always
    environment:
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_IDS=
      - PLANT_ID=
      - LATITUDE=
      - LONGITUDE=
      - TZ=Europe/Madrid
      - API_URL=https://uni001eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1/station-kiosk-file
      - HEALTHCHECK_URL=https://hc-ping.com/xxx