services:
  solar-monitor:
    image: ghcr.io/acamposcar/solar:latest
    container_name: solar-monitor
    restart: always
    environment:
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_IDS=
      - PLANT_ID=
      - LATITUDE=
      - LONGITUDE=